# Inicialização do Projeto

## Objetivo

Este notebook corresponde à fase inicial do projeto e tem como objetivo carregar o conjunto de dados, configurar o ambiente de trabalho e realizar as primeiras transformações necessárias para facilitar as etapas seguintes.

O projeto tem como foco a análise do mercado imobiliário português, utilizando um conjunto de dados composto por anúncios de imóveis localizados em Portugal.

Nesta fase serão realizadas as seguintes tarefas:

- Importação das bibliotecas necessárias;
- Carregamento do dataset;
- Configuração do ambiente de análise;
- Renomeação das variáveis;
- Conversão dos tipos de dados;
- Criação de variáveis derivadas;
- Criação de uma versão inicial do dataset para análise.

Esta etapa tem como objetivo preparar uma base de trabalho organizada e consistente para as fases seguintes da metodologia CRISP-DM.

In [1]:
# 1. IMPORTAR BIBLIOTECAS


import pandas as pd
import numpy as np

In [2]:
# 2. CARREGAR DATASET

path = "/kaggle/input/datasets/luvathoms/portugal-real-estate-2024/portugal_listinigs.csv"

df = pd.read_csv(path)

print("Dimensão:", df.shape)
display(df.head())

Dimensão: (135536, 25)

/tmp/ipykernel_16/258059624.py:5: DtypeWarning: Columns (9,10,12,13,14,15,16,20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

,Price,District,City,Town,Type,EnergyCertificate,GrossArea,TotalArea,Parking,HasParking,...,Elevator,ElectricCarsCharging,TotalRooms,NumberOfBedrooms,NumberOfWC,ConservationStatus,LivingArea,LotSize,BuiltArea,NumberOfBathrooms
0,780000.0,Vila Real,Valpaços,Carrazedo de Montenegro e Curros,Farm,NC,200.0,552450.0,0.0,False,...,False,NaN,NaN,NaN,NaN,NaN,120.0,NaN,NaN,0.0
1,223000.0,Faro,São Brás de Alportel,São Brás de Alportel,Apartment,A+,NaN,81.0,1.0,True,...,True,NaN,2.0,NaN,NaN,NaN,81.0,NaN,NaN,2.0
2,228000.0,Faro,São Brás de Alportel,São Brás de Alportel,Apartment,A+,NaN,108.0,1.0,True,...,True,NaN,2.0,NaN,NaN,NaN,108.0,NaN,NaN,2.0
3,250000.0,Faro,São Brás de Alportel,São Brás de Alportel,Apartment,A+,NaN,114.0,1.0,True,...,True,NaN,2.0,NaN,NaN,NaN,114.0,NaN,NaN,0.0
4,250000.0,Faro,São Brás de Alportel,São Brás de Alportel,Apartment,A+,NaN,114.0,1.0,True,...,True,NaN,2.0,NaN,NaN,NaN,114.0,NaN,NaN,2.0

In [3]:
# 3. RENOMEAR COLUNAS


df.columns = [
    "price",
    "district",
    "city",
    "town",
    "type",
    "energy_certificate",
    "gross_area",
    "total_area",
    "parking",
    "has_parking",
    "floor",
    "construction_year",
    "energy_efficiency_level",
    "publish_date",
    "garage",
    "elevator",
    "electric_cars_charging",
    "total_rooms",
    "number_of_bedrooms",
    "number_of_wc",
    "conservation_status",
    "living_area",
    "lot_size",
    "built_area",
    "number_of_bathrooms"
]

df.head()

,price,district,city,town,type,energy_certificate,gross_area,total_area,parking,has_parking,...,elevator,electric_cars_charging,total_rooms,number_of_bedrooms,number_of_wc,conservation_status,living_area,lot_size,built_area,number_of_bathrooms
0,780000.0,Vila Real,Valpaços,Carrazedo de Montenegro e Curros,Farm,NC,200.0,552450.0,0.0,False,...,False,NaN,NaN,NaN,NaN,NaN,120.0,NaN,NaN,0.0
1,223000.0,Faro,São Brás de Alportel,São Brás de Alportel,Apartment,A+,NaN,81.0,1.0,True,...,True,NaN,2.0,NaN,NaN,NaN,81.0,NaN,NaN,2.0
2,228000.0,Faro,São Brás de Alportel,São Brás de Alportel,Apartment,A+,NaN,108.0,1.0,True,...,True,NaN,2.0,NaN,NaN,NaN,108.0,NaN,NaN,2.0
3,250000.0,Faro,São Brás de Alportel,São Brás de Alportel,Apartment,A+,NaN,114.0,1.0,True,...,True,NaN,2.0,NaN,NaN,NaN,114.0,NaN,NaN,0.0
4,250000.0,Faro,São Brás de Alportel,São Brás de Alportel,Apartment,A+,NaN,114.0,1.0,True,...,True,NaN,2.0,NaN,NaN,NaN,114.0,NaN,NaN,2.0

In [4]:
# 4. CONVERTER TIPOS DE DADOS

# Data
df["publish_date"] = pd.to_datetime(
    df["publish_date"],
    errors="coerce"
)

# Booleanas
boolean_cols = [
    "has_parking",
    "garage",
    "elevator",
    "electric_cars_charging"
]

for col in boolean_cols:
    df[col] = (
        df[col]
        .astype("string")
        .str.lower()
        .str.strip()
        .replace({
            "true": True,
            "false": False,
            "yes": True,
            "no": False,
            "sim": True,
            "não": False,
            "nao": False,
            "nan": pd.NA,
            "<na>": pd.NA
        })
    )

    df[col] = df[col].astype("boolean")

# Categóricas
categorical_cols = [
    "district",
    "city",
    "town",
    "type",
    "energy_certificate",
    "floor",
    "energy_efficiency_level",
    "conservation_status"
]

for col in categorical_cols:
    df[col] = df[col].astype("category")

# Numéricas inteiras quando fizer sentido
integer_cols = [
    "parking",
    "construction_year",
    "total_rooms",
    "number_of_bedrooms",
    "number_of_wc",
    "number_of_bathrooms"
]

for col in integer_cols:
    df[col] = df[col].astype("Int64")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135536 entries, 0 to 135535
Data columns (total 25 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   price                    135236 non-null  float64
 1   district                 135536 non-null  category
 2   city                     135536 non-null  category
 3   town                     135534 non-null  category
 4   type                     135520 non-null  category
 5   energy_certificate       135522 non-null  category
 6   gross_area               27638 non-null   float64
 7   total_area               127153 non-null  float64
 8   parking                  135342 non-null  Int64
 9   has_parking              68215 non-null   boolean
 10  floor                    27929 non-null   category
 11  construction_year        88021 non-null   Int64
 12  energy_efficiency_level  67289 non-null   category
 13  publish_date             28779 non-null   datetime64[ns]
 14  garage                   67289 non-null   boolean
 15  elevator                 135504 non-null  boolean
 16  electric_cars_charging   67289 non-null   boolean
 17  total_rooms              73244 non-null   Int64
 18  number_of_bedrooms       47041 non-null   Int64
 19  number_of_wc             57256 non-null   Int64
 20  conservation_status      19292 non-null   category
 21  living_area              104952 non-null  float64
 22  lot_size                 39583 non-null   float64
 23  built_area               26617 non-null   float64
 24  number_of_bathrooms      128700 non-null  Int64
dtypes: Int64(6), boolean(4), category(8), datetime64[ns](1), float64(6)
memory usage: 16.6 MB

In [5]:
# 5. RESUMO DOS VALORES EM FALTA


missing = pd.DataFrame({
    "coluna": df.columns,
    "tipo": df.dtypes.astype(str).values,
    "valores_em_falta": df.isna().sum().values,
    "percentagem_em_falta": (df.isna().mean().values * 100).round(2),
    "valores_unicos": df.nunique(dropna=True).values
})

missing = missing.sort_values(
    by="percentagem_em_falta",
    ascending=False
)

display(missing)

,coluna,tipo,valores_em_falta,percentagem_em_falta,valores_unicos
20,conservation_status,category,116244,85.77,6
23,built_area,float64,108919,80.36,7296
6,gross_area,float64,107898,79.61,2267
10,floor,category,107607,79.39,19
13,publish_date,datetime64[ns],106757,78.77,27409
22,lot_size,float64,95953,70.80,6778
18,number_of_bedrooms,Int64,88495,65.29,22
19,number_of_wc,Int64,78280,57.76,27
14,garage,boolean,68247,50.35,2
12,energy_efficiency_level,category,68247,50.35,11
16,electric_cars_charging,boolean,68247,50.35,2
9,has_parking,boolean,67321,49.67,2
17,total_rooms,Int64,62292,45.96,58
11,construction_year,Int64,47515,35.06,125
21,living_area,float64,30584,22.57,3030
7,total_area,float64,8383,6.19,7305
24,number_of_bathrooms,Int64,6836,5.04,46
0,price,float64,300,0.22,4754
8,parking,Int64,194,0.14,4
15,elevator,boolean,32,0.02,2
4,type,category,16,0.01,21
5,energy_certificate,category,14,0.01,12
2,city,category,0,0.00,275
3,town,category,2,0.00,2263
1,district,category,0,0.00,27

In [6]:
# 6. CRIAR VARIÁVEIS NOVAS

# Preço por metro quadrado
df["price_m2"] = df["price"] / df["total_area"]

# Idade do imóvel
df["property_age"] = 2026 - df["construction_year"]

# Ano e mês da publicação
df["publish_year"] = df["publish_date"].dt.year
df["publish_month"] = df["publish_date"].dt.month

# Evitar valores impossíveis
df.loc[df["price"] <= 0, "price"] = np.nan
df.loc[df["total_area"] <= 0, "total_area"] = np.nan
df.loc[df["price_m2"] <= 0, "price_m2"] = np.nan
df.loc[df["property_age"] < 0, "property_age"] = np.nan

display(df.head())

,price,district,city,town,type,energy_certificate,gross_area,total_area,parking,has_parking,...,number_of_wc,conservation_status,living_area,lot_size,built_area,number_of_bathrooms,price_m2,property_age,publish_year,publish_month
0,780000.0,Vila Real,Valpaços,Carrazedo de Montenegro e Curros,Farm,NC,200.0,552450.0,0,False,...,<NA>,NaN,120.0,NaN,NaN,0,1.411892,<NA>,NaN,NaN
1,223000.0,Faro,São Brás de Alportel,São Brás de Alportel,Apartment,A+,NaN,81.0,1,True,...,<NA>,NaN,81.0,NaN,NaN,2,2753.086420,<NA>,NaN,NaN
2,228000.0,Faro,São Brás de Alportel,São Brás de Alportel,Apartment,A+,NaN,108.0,1,True,...,<NA>,NaN,108.0,NaN,NaN,2,2111.111111,<NA>,NaN,NaN
3,250000.0,Faro,São Brás de Alportel,São Brás de Alportel,Apartment,A+,NaN,114.0,1,True,...,<NA>,NaN,114.0,NaN,NaN,0,2192.982456,<NA>,NaN,NaN
4,250000.0,Faro,São Brás de Alportel,São Brás de Alportel,Apartment,A+,NaN,114.0,1,True,...,<NA>,NaN,114.0,NaN,NaN,2,2192.982456,<NA>,NaN,NaN

In [7]:
# Dimensão do dataset
print(f'Número de linhas: {df.shape[0]}')
print(f'Número de colunas: {df.shape[1]}')

# Informações gerais
df.info()

Número de linhas: 135536
Número de colunas: 29
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135536 entries, 0 to 135535
Data columns (total 29 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   price                    135236 non-null  float64
 1   district                 135536 non-null  category
 2   city                     135536 non-null  category
 3   town                     135534 non-null  category
 4   type                     135520 non-null  category
 5   energy_certificate       135522 non-null  category
 6   gross_area               27638 non-null   float64
 7   total_area               126220 non-null  float64
 8   parking                  135342 non-null  Int64
 9   has_parking              68215 non-null   boolean
 10  floor                    27929 non-null   category
 11  construction_year        88021 non-null   Int64
 12  energy_efficiency_level  67289 non-null   category
 13  publish_date             28779 non-null   datetime64[ns]
 14  garage                   67289 non-null   boolean
 15  elevator                 135504 non-null  boolean
 16  electric_cars_charging   67289 non-null   boolean
 17  total_rooms              73244 non-null   Int64
 18  number_of_bedrooms       47041 non-null   Int64
 19  number_of_wc             57256 non-null   Int64
 20  conservation_status      19292 non-null   category
 21  living_area              104952 non-null  float64
 22  lot_size                 39583 non-null   float64
 23  built_area               26617 non-null   float64
 24  number_of_bathrooms      128700 non-null  Int64
 25  price_m2                 126852 non-null  float64
 26  property_age             88021 non-null   Int64
 27  publish_year             28779 non-null   float64
 28  publish_month            28779 non-null   float64
dtypes: Int64(7), boolean(4), category(8), datetime64[ns](1), float64(9)
memory usage: 20.9 MB

In [8]:
nulos = df.isnull().sum()

display(
    nulos.sort_values(ascending=False)
)

conservation_status        116244
built_area                 108919
gross_area                 107898
floor                      107607
publish_month              106757
publish_date               106757
publish_year               106757
lot_size                    95953
number_of_bedrooms          88495
number_of_wc                78280
energy_efficiency_level     68247
garage                      68247
electric_cars_charging      68247
has_parking                 67321
total_rooms                 62292
construction_year           47515
property_age                47515
living_area                 30584
total_area                   9316
price_m2                     8684
number_of_bathrooms          6836
price                         300
parking                       194
elevator                       32
type                           16
energy_certificate             14
town                            2
city                            0
district                        0
dtype: int64

In [9]:
percentagem_nulos = (
    df.isnull()
      .mean()
      .mul(100)
      .round(2)
)

display(
    percentagem_nulos.sort_values(
        ascending=False
    )
)

conservation_status        85.77
built_area                 80.36
gross_area                 79.61
floor                      79.39
publish_month              78.77
publish_date               78.77
publish_year               78.77
lot_size                   70.80
number_of_bedrooms         65.29
number_of_wc               57.76
energy_efficiency_level    50.35
garage                     50.35
electric_cars_charging     50.35
has_parking                49.67
total_rooms                45.96
construction_year          35.06
property_age               35.06
living_area                22.57
total_area                  6.87
price_m2                    6.41
number_of_bathrooms         5.04
price                       0.22
parking                     0.14
elevator                    0.02
type                        0.01
energy_certificate          0.01
city                        0.00
town                        0.00
district                    0.00
dtype: float64

In [10]:
resumo_nulos = pd.DataFrame({

    'nulos': df.isnull().sum(),

    'percentagem_nulos': (
        df.isnull()
          .mean()
          * 100
    ).round(2)

})

resumo_nulos = resumo_nulos.sort_values(
    by='percentagem_nulos',
    ascending=False
)

display(resumo_nulos)
duplicados = df.duplicated().sum()

print(f'Número de duplicados: {duplicados}')

                          nulos  percentagem_nulos
conservation_status      116244              85.77
built_area               108919              80.36
gross_area               107898              79.61
floor                    107607              79.39
publish_month            106757              78.77
publish_date             106757              78.77
publish_year             106757              78.77
lot_size                  95953              70.80
number_of_bedrooms        88495              65.29
number_of_wc              78280              57.76
energy_efficiency_level   68247              50.35
garage                    68247              50.35
electric_cars_charging    68247              50.35
has_parking               67321              49.67
total_rooms               62292              45.96
construction_year         47515              35.06
property_age              47515              35.06
living_area               30584              22.57
total_area                 9316               6.87
price_m2                   8684               6.41
number_of_bathrooms        6836               5.04
price                       300               0.22
parking                     194               0.14
elevator                     32               0.02
type                         16               0.01
energy_certificate           14               0.01
city                          0               0.00
town                          2               0.00
district                      0               0.00

Número de duplicados: 9011

In [11]:
duplicados = df.duplicated().sum()

print(f'Número de duplicados: {duplicados}')

Número de duplicados: 9011

In [12]:
percentagem_duplicados = round(

    (df.duplicated().sum() / len(df)) * 100,

    2

)

print(
    f'Percentagem de duplicados: {percentagem_duplicados}%'
)

Percentagem de duplicados: 6.65%

In [13]:
display(

    df[df.duplicated()]

)

,price,district,city,town,type,energy_certificate,gross_area,total_area,parking,has_parking,...,number_of_wc,conservation_status,living_area,lot_size,built_area,number_of_bathrooms,price_m2,property_age,publish_year,publish_month
93,120000.0,Faro,Tavira,Tavira (Santa Maria e Santiago),Land,NC,NaN,210.0,0,False,...,<NA>,NaN,NaN,NaN,NaN,0,571.428571,<NA>,NaN,NaN
152,120000.0,Faro,Tavira,Tavira (Santa Maria e Santiago),Land,NC,NaN,210.0,0,False,...,<NA>,NaN,NaN,NaN,NaN,0,571.428571,<NA>,NaN,NaN
153,120000.0,Faro,Tavira,Tavira (Santa Maria e Santiago),Land,NC,NaN,210.0,0,False,...,<NA>,NaN,NaN,NaN,NaN,0,571.428571,<NA>,NaN,NaN
154,120000.0,Faro,Tavira,Tavira (Santa Maria e Santiago),Land,NC,NaN,210.0,0,False,...,<NA>,NaN,NaN,NaN,NaN,0,571.428571,<NA>,NaN,NaN
155,120000.0,Faro,Tavira,Tavira (Santa Maria e Santiago),Land,NC,NaN,210.0,0,False,...,<NA>,NaN,NaN,NaN,NaN,0,571.428571,<NA>,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135483,450000.0,Lisboa,Sintra,Colares,Land,NC,NaN,NaN,0,<NA>,...,0,NaN,NaN,1720.0,NaN,0,NaN,<NA>,NaN,NaN
135502,198000.0,Santarém,Benavente,Samora Correia,Land,NC,NaN,NaN,0,<NA>,...,0,NaN,NaN,307.0,NaN,0,NaN,<NA>,NaN,NaN
135506,79000.0,Santarém,Entroncamento,Nossa Senhora de Fátima,Land,NC,NaN,NaN,0,<NA>,...,0,NaN,NaN,540.0,NaN,0,NaN,<NA>,NaN,NaN
135521,36000.0,Vila Real,Sabrosa,Paços,Land,NC,NaN,90.0,0,<NA>,...,0,NaN,NaN,300.0,240.88,0,400.000000,<NA>,NaN,NaN
135535,35000.0,Vila Real,Valpaços,Algeriz,Land,NC,NaN,100.0,0,<NA>,...,0,NaN,NaN,100.0,NaN,0,350.000000,<NA>,NaN,NaN

In [14]:
df = df.drop_duplicates()

In [15]:
valores_unicos = pd.DataFrame({

    'valores_unicos': df.nunique()

})

valores_unicos = valores_unicos.sort_values(

    by='valores_unicos'

)

display(valores_unicos)

                         valores_unicos
elevator                              2
garage                                2
has_parking                           2
electric_cars_charging                2
parking                               4
conservation_status                   6
publish_year                          7
energy_efficiency_level              11
publish_month                        12
energy_certificate                   12
floor                                19
type                                 21
number_of_bedrooms                   22
district                             27
number_of_wc                         27
number_of_bathrooms                  46
total_rooms                          58
property_age                        125
construction_year                   125
city                                275
town                               2263
gross_area                         2267
living_area                        3030
price                              4754
lot_size                           6778
built_area                         7296
total_area                         7301
publish_date                      27409
price_m2                          49843

In [16]:
display(

    df.describe()

)

,price,gross_area,total_area,parking,construction_year,publish_date,total_rooms,number_of_bedrooms,number_of_wc,living_area,lot_size,built_area,number_of_bathrooms,price_m2,property_age,publish_year,publish_month
count,1.262420e+05,2.601400e+04,1.178470e+05,126379.0,83259.0,27484,68784.0,43780.0,53180.0,9.806300e+04,3.682100e+04,2.480300e+04,120027.0,1.184610e+05,83259.0,27484.000000,27484.000000
mean,3.707856e+05,2.927941e+03,5.544579e+05,0.544964,1988.803493,2024-08-26 20:19:06.224937216,3.237599,2.673572,0.433377,1.441857e+03,5.718602e+04,3.174110e+03,1.544128,inf,37.196507,2024.075171,7.416024
min,1.000000e+00,-7.000000e+00,1.000000e+00,0.0,1900.0,2018-04-09 05:48:21.907000,0.0,0.0,-15.0,0.000000e+00,0.000000e+00,-1.000000e+00,-13.0,1.058286e-06,1.0,2018.000000,1.000000
25%,8.500000e+04,1.000000e+02,9.200000e+01,0.0,1972.0,2024-06-27 21:18:04.771500032,2.0,2.0,0.0,8.000000e+01,2.610000e+02,1.039750e+02,0.0,2.868852e+02,18.0,2024.000000,5.000000
50%,2.100000e+05,1.630000e+02,1.600000e+02,0.0,1993.0,2024-10-07 15:21:06.908000,3.0,3.0,0.0,1.180000e+02,6.900000e+02,1.670000e+02,1.0,1.493056e+03,33.0,2024.000000,8.000000
75%,3.900000e+05,2.960000e+02,5.200000e+02,1.0,2008.0,2024-11-29 15:29:03.500749824,4.0,3.0,1.0,2.050000e+02,2.940000e+03,3.000000e+02,2.0,2.978142e+03,54.0,2024.000000,11.000000
max,1.380000e+09,1.275000e+07,6.142007e+10,3.0,2025.0,2025-01-28 19:07:18.900000,2751.0,21.0,59.0,5.429000e+06,9.923010e+08,1.275000e+07,131.0,inf,126.0,2025.000000,12.000000
std,3.935295e+06,1.189093e+05,1.789672e+08,0.839166,26.58722,NaN,10.819638,1.792918,1.017005,3.580241e+04,5.374958e+06,1.226149e+05,1.738664,NaN,26.58722,0.474917,3.700653

In [17]:
display(

    df.describe(
        include='category'
    )

)

,district,city,town,type,energy_certificate,floor,energy_efficiency_level,conservation_status
count,126525,126525,126523,126510,126512,26099,62613,18024
unique,27,275,2263,21,12,19,11,6
top,Lisboa,Lisboa,Paranhos,Apartment,NC,Ground Floor,NC,New
freq,29906,8061,1880,43984,56403,6541,28786,6068

In [18]:
data_quality = pd.DataFrame({

    'tipo': df.dtypes,

    'nulos': df.isnull().sum(),

    'percentagem_nulos': (
        df.isnull()
          .mean()
          * 100
    ).round(2),

    'duplicados': [

        df.duplicated().sum()

    ] * len(df.columns),

    'valores_unicos': df.nunique()

})

data_quality = data_quality.sort_values(

    by='percentagem_nulos',

    ascending=False

)

display(data_quality)

,tipo,nulos,percentagem_nulos,duplicados,valores_unicos
conservation_status,category,108501,85.75,0,6
built_area,float64,101722,80.40,0,7296
gross_area,float64,100511,79.44,0,2267
floor,category,100426,79.37,0,19
publish_month,float64,99041,78.28,0,12
publish_date,datetime64[ns],99041,78.28,0,27409
publish_year,float64,99041,78.28,0,7
lot_size,float64,89704,70.90,0,6778
number_of_bedrooms,Int64,82745,65.40,0,22
number_of_wc,Int64,73345,57.97,0,27
energy_efficiency_level,category,63912,50.51,0,11
garage,boolean,63912,50.51,0,2
electric_cars_charging,boolean,63912,50.51,0,2
has_parking,boolean,62643,49.51,0,2
total_rooms,Int64,57741,45.64,0,58
construction_year,Int64,43266,34.20,0,125
property_age,Int64,43266,34.20,0,125
living_area,float64,28462,22.50,0,3030
total_area,float64,8678,6.86,0,7301
price_m2,float64,8064,6.37,0,49843
number_of_bathrooms,Int64,6498,5.14,0,46
price,float64,283,0.22,0,4754
parking,Int64,146,0.12,0,4
elevator,boolean,30,0.02,0,2
type,category,15,0.01,0,21
energy_certificate,category,13,0.01,0,12
city,category,0,0.00,0,275
town,category,2,0.00,0,2263
district,category,0,0.00,0,27

In [19]:
df = df.dropna(subset=["price"])

In [20]:
data_quality = pd.DataFrame({

    'tipo': df.dtypes,

    'nulos': df.isnull().sum(),

    'percentagem_nulos': (
        df.isnull()
          .mean()
          * 100
    ).round(2),

    'duplicados': [

        df.duplicated().sum()

    ] * len(df.columns),

    'valores_unicos': df.nunique()

})

data_quality = data_quality.sort_values(

    by='percentagem_nulos',

    ascending=False

)

display(data_quality)

,tipo,nulos,percentagem_nulos,duplicados,valores_unicos
conservation_status,category,108263,85.76,0,6
built_area,float64,101479,80.38,0,7292
gross_area,float64,100249,79.41,0,2267
floor,category,100224,79.39,0,19
publish_month,float64,98770,78.24,0,12
publish_date,datetime64[ns],98770,78.24,0,27397
publish_year,float64,98770,78.24,0,7
lot_size,float64,89498,70.89,0,6771
number_of_bedrooms,Int64,82586,65.42,0,22
number_of_wc,Int64,73207,57.99,0,27
energy_efficiency_level,category,63776,50.52,0,11
garage,boolean,63776,50.52,0,2
electric_cars_charging,boolean,63776,50.52,0,2
has_parking,boolean,62496,49.50,0,2
total_rooms,Int64,57637,45.66,0,57
construction_year,Int64,43124,34.16,0,125
property_age,Int64,43124,34.16,0,125
living_area,float64,28434,22.52,0,3026
total_area,float64,8671,6.87,0,7294
price_m2,float64,7781,6.16,0,49843
number_of_bathrooms,Int64,6496,5.15,0,46
parking,Int64,146,0.12,0,4
elevator,boolean,30,0.02,0,2
energy_certificate,category,13,0.01,0,12
type,category,15,0.01,0,21
price,float64,0,0.00,0,4754
district,category,0,0.00,0,27
city,category,0,0.00,0,275
town,category,2,0.00,0,2263

In [21]:
# Selecionar variáveis numéricas

numericas = df.select_dtypes(
    include=["int64", "float64"]
).columns

print(numericas)

Index(['price', 'gross_area', 'total_area', 'parking', 'construction_year',
       'total_rooms', 'number_of_bedrooms', 'number_of_wc', 'living_area',
       'lot_size', 'built_area', 'number_of_bathrooms', 'price_m2',
       'property_age', 'publish_year', 'publish_month'],
      dtype='object')

In [22]:
# Método IQR

Q1 = df[numericas].quantile(0.25)

Q3 = df[numericas].quantile(0.75)

IQR = Q3 - Q1

outliers = (

    ((df[numericas] < (Q1 - 1.5 * IQR)) |

     (df[numericas] > (Q3 + 1.5 * IQR)))

).sum()

outliers = outliers.sort_values(
    ascending=False
)

display(outliers)

total_area             20084
living_area            11236
price                  10582
number_of_bedrooms      7795
parking                 6791
lot_size                5150
publish_year            5082
price_m2                4951
gross_area              2834
built_area              2786
total_rooms             2722
number_of_bathrooms     2581
number_of_wc            1943
construction_year        338
property_age             338
publish_month              0
dtype: Int64

In [23]:
percentagem_outliers = (

    outliers / len(df) * 100

).round(2)

display(percentagem_outliers)

total_area             15.91
living_area              8.9
price                   8.38
number_of_bedrooms      6.17
parking                 5.38
lot_size                4.08
publish_year            4.03
price_m2                3.92
gross_area              2.24
built_area              2.21
total_rooms             2.16
number_of_bathrooms     2.04
number_of_wc            1.54
construction_year       0.27
property_age            0.27
publish_month            0.0
dtype: Float64

In [24]:
resumo_outliers = pd.DataFrame({

    "Outliers": outliers,

    "Percentagem (%)": percentagem_outliers

})

resumo_outliers = resumo_outliers.sort_values(

    by="Percentagem (%)",

    ascending=False

)

display(resumo_outliers)

                     Outliers  Percentagem (%)
total_area              20084            15.91
living_area             11236              8.9
price                   10582             8.38
number_of_bedrooms       7795             6.17
parking                  6791             5.38
lot_size                 5150             4.08
publish_year             5082             4.03
price_m2                 4951             3.92
gross_area               2834             2.24
built_area               2786             2.21
total_rooms              2722             2.16
number_of_bathrooms      2581             2.04
number_of_wc             1943             1.54
construction_year         338             0.27
property_age              338             0.27
publish_month               0              0.0

# Conclusão

A fase de inicialização foi concluída com sucesso.

O conjunto de dados foi carregado e estruturado, permitindo obter uma primeira visão da informação disponível e preparar o ambiente de trabalho para as próximas etapas do projeto.

Foram efetuadas transformações iniciais, nomeadamente a uniformização das variáveis, a conversão dos respetivos tipos de dados e a criação de novas variáveis de apoio à análise.

Nas fases seguintes será realizada uma análise mais aprofundada do conjunto de dados, incluindo a avaliação da sua qualidade, a identificação de padrões e a extração de insights relevantes sobre o mercado imobiliário português.

---

**Última atualização:** 16/06/2026

**Autor:** Luís Figueira